services:
  db:
    image: postgres:15
    container_name: postgres-sql
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=regression
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgresql/init:/docker-entrypoint-initdb.d

  py:
    build: ./python
    container_name: pyclient
    depends_on:
      - db
    working_dir: /app/python/scripts
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  pgdata: